### ISSUE TITLE
Arrows only work a max of 4 clicks

### ISSUE THREAD

**Issue by janeslee** [bmcmahen/react-gesture-gallery#2]
The arrows to navigate through the pictures only work a maximum of 4 clicks before the cursor has to exit the proximity, re-enter, and allow the arrows to reload

**Comment by bmcmahen** [comment]
I think what's happening is the timeout isn't cancelled when hovering over the arrows. This shouldn't be a difficult fix -- will try to get to this today and post an update. Thanks for the bug report.

**Comment by bmcmahen** [comment]
Version 1.0.1 should fix this. Let me know if you continue to have problems.
