### ISSUE TITLE
BreadCrumb Overflow

### ISSUE THREAD

**Issue by JuanMugicaExt** [bmcmahen/react-gesture-gallery#4]
Hey bmc,

First off love the component, simple and easy to use, but when dealing with a large number of images, especially when rendering the gallery in a modal window, it's easy for the breadcrumbs to overflow the dimensions of their container. Would there be any interest in looking for a solution to this? I was thinking something along the lines of displaying the (children/(children/x))th breadcrumb and updating at +-(children/x). This would ensure a max of (x+(x-1)) children displayed and update accordingly to the number of displayed children. 

thoughts? 
Cheers!

**Comment by bmcmahen** [comment]
That's a great point. I hadn't really considered that scenario. I'm definitely interested in a potential solution - i suppose the breadcrumbs could be limited to a max-width and then cycle into view. Hmm. Any ideas yourself?

**Comment by bmcmahen** [comment]
I guess the easiest solution for now would be to just disable them as it might not make a ton of sense within the context of a very long series of images anyway.

**Comment by JuanMugicaExt** [comment]
The way i was able to sort it out was just by adding an arbitrary number x and then making the breadcrumb length Math.min(children.length,x), and the index input (index%x). This way if the array is ever shorter than our desired breadcrumb max it will display the shorter one. (Index%x) makes sure than we we exceed our breadcrumb max in index it will come back to the first breadcrumb! Worked like a charm and should be rather simple to implement. Once again wanted to give Kudos to the simplicity and usability of this gallery module.

**Comment by JuanMugicaExt** [comment]
Also for usability purposes x could be set to an int.max at first so if it is not passed as a parameter the user will never have to worry about it for simpler implementations of the gallery. This way Math.min will always choose children length and index%x will always be index.

**Comment by bmcmahen** [comment]
that's a clever solution... not sure if it's something i'd want to bake into this component, but def might be worth noting in the readme.
